### PR TITLE
don't set almostPosn.w to 0?

### PR DESCRIPTION
**Pull request by david-vanderson**
Two machines I have show a bad visual artifact when a zoomed in sprite is covering the top-left corner of the screen.  Commenting out these lines fixes it.  I don't understand what this code is doing, and I'm having trouble testing layer wrapping.  Any advice?

### CODE REVIEW

**Comment by david-vanderson** [comment]
I now realize that commenting out those lines messes up the normal rendering.  I'm somewhat lost here.  How does changing the w coordinate work with 2D rendering?

**Comment by jeapostrophe** [comment]
You need four dimensions to do affine transformations in three dimensions (we need affinity for translations.) `w` really needs to be `0`. Can you show me the artifact? I don't quite understand the circumstance.

**Comment by david-vanderson** [comment]
I've added a test file to the pull request that trips the issue for me.  When I run it, the whole window is filled with blue even though the sprite is only 3x3.  Somehow when sprites are covering the top-left corner of the window they are magnified by a large amount.

Does that help?

**Comment by jeapostrophe** [comment]
Can you send me a screenshot of what you see? (I don't see it. You said that it only happens on some machines, right? It would be nice to know their OpenGL drivers/versions/etc.)

**Comment by david-vanderson** [comment]
One is a windows laptop with NVIDIA NVS 5400M driver 382.05 that says:
You are using OpenGL '(4 5 0) with gl-backend-version of 3.3

The other is a windows desktop with NVIDIA GeForce GTX 750 Ti driver 388.43 that says the same:
You are using OpenGL '(4 5 0) with gl-backend-version of 3.3

Is there more information I can get you?  I'm attaching a screenshot.
artifact

**Comment by david-vanderson** [comment]
Not sure if it helps, but if I make the sprite 2x2 and position it at (- 0.0 (/ W 2) 1.0) (- 0.0 (/ H 2) 1.0), then it covers only a quarter of the screen, so it seems they are being magnified but there is a limit:
artifact2

**Comment by jeapostrophe** [comment]
Try changing the `.w` component to a large negative number, like `-128.0`. (I mis-wrote before, `.w` is supposed to be `1` normally, but if we move it around then it will push the object out of the view space. I intended `0` to be behind the camera, but it looks like there might be enough rounding that makes it just barely infront of the camera. If we make it large and negative then it is definitely behind the camera. If negative doesn't work, I may have the sign wrong, so try big and positive.)

**Comment by david-vanderson** [comment]
Thank you!  -128.0 works like a charm.  I will update the pull request.

(I tried +128.0 as well, that seemed to produce very thin horizontal and vertical lines occasionally)

Thanks again!

**Comment by jeapostrophe** [comment]
Awesome, and it looks fine on the other devices too? (I'll test here anyways)

**Comment by david-vanderson** [comment]
Yes, sorry I didn't say.  It looks fine (no regressions) on the mac I have.  Thanks!

**Comment by jeapostrophe** [comment]
Excellent. Thanks.

**Pull request merged**
