### PR TITLE
cleanups and vertical line artifact fix

### PR DESCRIPTION
**Pull request by david-vanderson**
I'll attach a screenshot of the vertical line artifacts I'm seeing.

### CODE REVIEW

**Comment by david-vanderson** [comment]
vertical_lines

**Comment by david-vanderson** [comment]
I only see them on my Windows machine, and I get different numbers of them depending on canvas size, but this fix seems to work at least for me.

**Comment by david-vanderson** [comment]
[ml-test.txt](https://github.com/jeapostrophe/mode-lambda/files/1753181/ml-test.txt)
Test file I'm using (rename to .rkt)

**Comment by jeapostrophe** [comment]
Thanks David, looks good.

**Comment by david-vanderson** [comment]
Thank you!

**Pull request merged**
