### PR TITLE
add padding keyword argument to compile-sprite-db

### PR DESCRIPTION
**Pull request by david-vanderson**

### CODE REVIEW

**Comment by david-vanderson** [comment]
This is the easiest way I know of to prevent color bleeding if the sprite atlas is big enough and you zoom the sprites small enough.  Probably most people won't need it but it's helping me.  Thanks!

**Comment by jeapostrophe** [comment]
What number did you find you needed?

**Comment by david-vanderson** [comment]
Wow you are too fast.  I was using 2, and then today I needed to bump it to 3 after adding some really large sprites.

**Comment by jeapostrophe** [comment]
I wonder if we could figure out a better default then... 5? Some % of the sprite? 4? 8? Seems like a power of 2 is a good idea.

**Comment by david-vanderson** [comment]
I don't have a good idea if there's a maximum that would be enough for all cases, so I figured this is the best option for now?

**Comment by jeapostrophe** [comment]
(I think we should still add the argument, I'm just thinking of changing the default too so it's more likely you never need it.)

**Comment by david-vanderson** [comment]
My guess is some power of two related to the total sprite atlas size?

**Comment by jeapostrophe** [comment]
I dunno. I'll accept the patch for now, and maybe we can revisit the default?

**Comment by david-vanderson** [comment]
Good plan.  Thanks!

**Pull request merged**
